version: '3.9'

services:

  proxy:
    build: ./docker-nginx
    ports:
    - 80:80
    - 443:443
    depends_on:
      - web
    volumes:
      - static_data:/static_data
    networks:
      - net100

  web:
    ports:
      - 8080:8000
      - 8000:8000
    expose:
      - 8000
    build: .
    command: gunicorn proj.wsgi --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_data:/static_data
    networks:
      - net100

volumes:
  static_data:

networks:
  net100: {}