# Generated by Django 4.1.5 on 2023-01-30 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_invite_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
