# Generated by Django 4.1.5 on 2023-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='confirm_date',
            field=models.DateTimeField(null=True),
        ),
    ]
