# Generated by Django 4.1.5 on 2023-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0005_alter_invite_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
